meta_product_name: “Pigeonhole”

meta_title: “Pigeonhole  home of amazing content cureted for you by your closest people”

meta_description: “World leader in personal content management and curation”

meta_image: “Logo.png” # should exist in `app/assets/images/`
